# Generated by Django 4.2.16 on 2024-11-11 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_list',
            field=models.ManyToManyField(related_name='friends', through='accounts.UserList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='friend',
        ),
        migrations.AlterField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlist',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
